# frozen_string_literal: true

# generado con pg_rails

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Public::MensajeContactosController do
  render_views
  # This should return the minimal set of attributes required to create a valid
  # MensajeContacto. As you add validations to MensajeContacto, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    attributes_for(:mensaje_contacto)
  end

  let(:invalid_attributes) do
    {
      nombre: nil
    }
  end

  let(:logged_user) { create :user, :developer }

  before do
    sign_in logged_user if logged_user.present?
  end

  describe 'routing' do
    it 'routes GET index correctly' do
      route = { get: '/public/mensaje_contactos' }
      expect(route).to route_to(controller: 'public/mensaje_contactos', action: 'index')
    end
  end

  describe 'GET #index' do
    subject do
      get :index, params: {}
    end

    let!(:mensaje_contacto) { create :mensaje_contacto }

    it 'returns a success response' do
      subject
      expect(response).to be_successful
    end

    context 'when user is not logged in' do
      let(:logged_user) { nil }

      it 'redirects to login path' do
        subject
        expect(response).to redirect_to(new_user_session_path)
      end
    end

    context 'when se pide el excel' do
      subject do
        get :index, params: {}, format: 'xlsx'
      end

      it 'returns a success response' do
        subject
        expect(response).to be_successful
      end
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      mensaje_contacto = create(:mensaje_contacto)
      get :show, params: { id: mensaje_contacto.to_param }
      expect(response).to be_successful
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      get :new, params: {}
      expect(response).to be_successful
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      mensaje_contacto = create(:mensaje_contacto)
      get :edit, params: { id: mensaje_contacto.to_param }
      expect(response).to be_successful
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new MensajeContacto' do
        expect do
          post :create, params: { mensaje_contacto: valid_attributes }
        end.to change(MensajeContacto, :count).by(1)
      end

      it 'redirects to the created mensaje_contacto' do
        post :create, params: { mensaje_contacto: valid_attributes }
        expect(response).to redirect_to(MensajeContacto.last.decorate.target_object)
      end
    end

    context 'with invalid params' do
      it 'returns a unprocessable_entity response' do
        post :create, params: { mensaje_contacto: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

      it 'renders the new template' do
        post :create, params: { mensaje_contacto: invalid_attributes }
        expect(response).to render_template(:new)
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) do
        attributes_for(:mensaje_contacto)
      end

      it 'updates the requested mensaje_contacto' do
        mensaje_contacto = create(:mensaje_contacto)
        put :update, params: { id: mensaje_contacto.to_param, mensaje_contacto: new_attributes }
        mensaje_contacto.reload
        expect(mensaje_contacto.nombre).to eq new_attributes[:nombre]
      end

      it 'redirects to the mensaje_contacto' do
        mensaje_contacto = create(:mensaje_contacto)
        put :update, params: { id: mensaje_contacto.to_param, mensaje_contacto: valid_attributes }
        expect(response).to redirect_to(mensaje_contacto.decorate.target_object)
      end
    end

    context 'with invalid params' do
      it 'returns a unprocessable_entity response' do
        mensaje_contacto = create(:mensaje_contacto)
        put :update, params: { id: mensaje_contacto.to_param, mensaje_contacto: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

      it 'renders the edit template' do
        mensaje_contacto = create(:mensaje_contacto)
        put :update, params: { id: mensaje_contacto.to_param, mensaje_contacto: invalid_attributes }
        expect(response).to render_template(:edit)
      end
    end
  end

  describe 'DELETE #destroy' do
    subject do
      delete :destroy, params: { id: mensaje_contacto.to_param }
    end

    let!(:mensaje_contacto) { create :mensaje_contacto }

    it 'destroys the requested mensaje_contacto' do
      expect { subject }.to change(MensajeContacto, :count).by(-1)
    end

    it 'redirects to the mensaje_contactos list' do
      subject
      expect(response).to redirect_to(public_mensaje_contactos_url)
    end
  end
end
