# generado con pg_rails

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe CategoriaDeCosasController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # CategoriaDeCosa. As you add validations to CategoriaDeCosa, be sure to
  # adjust the attributes here as well.


  let(:valid_attributes) {
    attributes_for(:categoria_de_cosa)
  }

  let(:invalid_attributes) {
    {
      nombre: nil,
      tipo: nil,
    }
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CategoriaDeCosasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:user) { create :user, :admin }
  before do
    sign_in user
  end


  describe "GET #index" do
    it "returns a success response" do
      create(:categoria_de_cosa)
      get :index, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      categoria_de_cosa = create(:categoria_de_cosa)
      get :show, params: {id: categoria_de_cosa.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: {}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      categoria_de_cosa = create(:categoria_de_cosa)
      get :edit, params: {id: categoria_de_cosa.to_param}, session: valid_session
      expect(response).to be_successful
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CategoriaDeCosa" do
        expect {
          post :create, params: {categoria_de_cosa: valid_attributes}, session: valid_session
        }.to change(CategoriaDeCosa, :count).by(1)
      end

      it "redirects to the created categoria_de_cosa" do
        post :create, params: {categoria_de_cosa: valid_attributes}, session: valid_session
        expect(response).to redirect_to(CategoriaDeCosa.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: {categoria_de_cosa: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        attributes_for(:categoria_de_cosa)
      }

      it "updates the requested categoria_de_cosa" do
        categoria_de_cosa = create(:categoria_de_cosa)
        put :update, params: {id: categoria_de_cosa.to_param, categoria_de_cosa: new_attributes}, session: valid_session
        categoria_de_cosa.reload
        expect(categoria_de_cosa.nombre).to eq new_attributes[:nombre]
      end

      it "redirects to the categoria_de_cosa" do
        categoria_de_cosa = create(:categoria_de_cosa)
        put :update, params: {id: categoria_de_cosa.to_param, categoria_de_cosa: valid_attributes}, session: valid_session
        expect(response).to redirect_to(categoria_de_cosa)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        categoria_de_cosa = create(:categoria_de_cosa)
        put :update, params: {id: categoria_de_cosa.to_param, categoria_de_cosa: invalid_attributes}, session: valid_session
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested categoria_de_cosa" do
      categoria_de_cosa = create(:categoria_de_cosa)
      expect {
        delete :destroy, params: {id: categoria_de_cosa.to_param}, session: valid_session
      }.to change(CategoriaDeCosa.without_deleted, :count).by(-1)
    end

    it "redirects to the categoria_de_cosas list" do
      categoria_de_cosa = create(:categoria_de_cosa)
      delete :destroy, params: {id: categoria_de_cosa.to_param}, session: valid_session
      expect(response).to redirect_to(categoria_de_cosas_url)
    end
  end

end
